// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['service']['HabitService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['service']['HabitService']['Delete'](arg1);
}

export function GetNode(arg1) {
  return window['go']['service']['HabitService']['GetNode'](arg1);
}

export function Index(arg1, arg2, arg3) {
  return window['go']['service']['HabitService']['Index'](arg1, arg2, arg3);
}

export function ToggleArchived(arg1) {
  return window['go']['service']['HabitService']['ToggleArchived'](arg1);
}

export function Update(arg1) {
  return window['go']['service']['HabitService']['Update'](arg1);
}

export function UpdateName(arg1, arg2) {
  return window['go']['service']['HabitService']['UpdateName'](arg1, arg2);
}
