// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';

export function Index(arg1:number,arg2:number):Promise<service.TrackerArrResult>;

export function Set(arg1:domain.SetTrackerDto):Promise<any>;
