// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['repository']['habitRepository']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['repository']['habitRepository']['Delete'](arg1);
}

export function Index(arg1, arg2) {
  return window['go']['repository']['habitRepository']['Index'](arg1, arg2);
}

export function ToggleArchived(arg1) {
  return window['go']['repository']['habitRepository']['ToggleArchived'](arg1);
}
