// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Create(arg1:domain.CreateHabitDTO):Promise<domain.Habit>;

export function Delete(arg1:number):Promise<void>;

export function Index(arg1:number,arg2:number):Promise<Array<domain.Habit>>;

export function ToggleArchived(arg1:number):Promise<void>;
