// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Index(arg1:number,arg2:number):Promise<Array<domain.Tracker>>;

export function Set(arg1:domain.SetTrackerDto):Promise<void>;
