// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Index(arg1, arg2) {
  return window['go']['repository']['trackerRepository']['Index'](arg1, arg2);
}

export function Set(arg1) {
  return window['go']['repository']['trackerRepository']['Set'](arg1);
}
